config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/about'

  resources :portfolios
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :description, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
    <nav>
        <div class="container">
            <%= image_tag("pizza.png", alt: "pizza logo", class:"logo-pizza")%>
            <ul>
                <h1> Pizzaria Noronha </h1>
                <li><a href="/">Home</a></li>
                <li><a href="/static_pages/about">Sobre nós</a></li>
                <li><a href="/portfolios">Cardápio</a></li>
            </ul>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Front-end</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Contrail+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render partial: "layouts/header" %></header>
    <p>
      <% if user_signed_in? %>
        Logado como <strong><%= current_user.email %></strong>.
        <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <!-- <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> -->
      <% end %>
      </p>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :portfolio_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :portfolio_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :portfolio_picture %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>


<section id="products">
  <div class="cardapio">
    <h2> Nosso Cardápio </h2>
  </div>
</section>

<section id="background-cardapio">
</section>

<section id="produtos-cardapio">
  <div class="container">
      <% @portfolios.each do |portfolio| %>
        <div class="product">
          <h2><a href="#"><%= portfolio.name%></a></h2>
          <h3><%= portfolio.description %></h3>
          <h3> R$ 45,00 </h3>
        </div>
      <% end %>
  </div>
</section>

<% if current_user %>
  <%= link_to 'New Portfolio', new_portfolio_path %>
<% end %>


<section id="pizzas-doces">
  <div class="cardapio">
    <h2>Pizzas Doces</h2>
  </div>
  <div id="background-pizza-doce-fundo">
  </div>
  <div class="container">
    <div class="products">
      <div class="product">
        <h2><a href="#">Pizza de Chocolate</a></h2>
        <h3>GRANULADO</h3>
        <h3> R$ 45,00 </h3>
      </div>
      <div class="product">
        <h2><a href="#">Pizza de Romeu e Julieta</a></h2>
        <h3>GOIABADA, QUEIJO</h3>
        <h3> R$ 45,00 </h3>
      </div>
      <div class="product">
        <h2><a href="#">Pizza de Banana</a></h2>
        <h3>CANELA</h3>
        <h3> R$ 45,00 </h3>
      </div>
    </div>
  </div>
</section>
<footer>
  <div class="container">
    <%= image_tag("whatsapp.png", alt: "whatsapp logo", class:"logo-whatsapp")%>
    <h2>Contate-nos<br> (21)99343-2299</h2>
    <a href="#"><%= image_tag("facebook.png", alt: "facebook logo", class:"logo-facebook")%></a>
  </div>
</footer>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio.description %>
</p>

<p>
    <%= image_tag(@portfolio.picture_url, :width => 600) if @portfolio.picture.present? %>
</p>

<p></p>

<% if current_user %> <%= link_to 'Edit', edit_portfolio_path(@portfolio) %> <% end %> |
<%= link_to 'Back', portfolios_path %>

app/views/static_pages/about.html.erb

<section id="sobre-nos">
    <div>
        <h2> Sobre nós </h2>
    </div>
</section>
<section id="background-sobre-nos">
</section>

<section class="container">
    <div id="sobre-nos-texto">
        <p> "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
        eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
        sunt in culpa qui 
        officia deserunt mollit anim id est laborum."
        </p>

        <p> "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
        eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
        sunt in culpa qui 
        officia deserunt mollit anim id est laborum."
        </p>
    </div>
    </section>
</section>
<footer>
  <div class="container">
    <%= image_tag("whatsapp.png", alt: "whatsapp logo", class:"logo-whatsapp")%>
    <h2>Contate-nos<br> (21)99343-2299</h2>
    <a href="#"><%= image_tag("facebook.png", alt: "facebook logo", class:"logo-facebook")%></a>
  </div>
</footer>

app/views/static_pages/home.html.erb
<html>
<body>
    
<section id = "chamada">
        <div class = "container">
            <h1>As melhores pizzas</h1>
            <h2>Na melhor pizzaria caseira</h2>
        </div>
    </section>
    
    <section id = "promocoes">
        <div class="apresentacao">
            <h3>Promoções</h3>
        </div>
        <div class="container">
            <div class="descricao">
                <h1>Não perca essa incrível</h1>
                <h2>promoção do dia</h2>
                <p>Pizza Portuguesa+Ice Tea de Pessego por apenas R$38,50</p>
            </div>
            <div class = "imagem">
                <%= image_tag("pizza_promo.jpg", alt: "promocao da pizza", class:"pizza-promo")%>
            </div>        
            </div>
    </section>

    <section id = "informacoes">
        <div class="apresentacao">
            <h3>Localização</h3>
        </div>
        <div class="container-infos">
            <p>Rua Noronha Torrezão, 102 - Santa Rosa, Niterói</p>
            <p>Aberto todos os dias das 18 horas até meia noite</p>
        </div>
    </section>
    </body>
</html>
<footer>
  <div class="container">
    <%= image_tag("whatsapp.png", alt: "whatsapp logo", class:"logo-whatsapp")%>
    <h2>Contate-nos<br> (21)99343-2299</h2>
    <a href="#"><%= image_tag("facebook.png", alt: "facebook logo", class:"logo-facebook")%></a>
  </div>
</footer>